### PR TITLE
Adding angular momentum flux expression and reference

### PR DESCRIPTION
**Pull request by akhairna**
Hi David,
    I have added the necessary details that you asked for and fixed a minor typo as well. Let me know if you need any other help. I haven't tried breaking anything yet. I will let you know if I try anything.

Regards,
Aniket Khairnar

### CODE REVIEW

**Review by davidtrestini — CHANGES_REQUESTED** [review]
Hi Aniket,

Thank you. All looks fine but it appears that the file "flux.txt" has line breaks in it. I'm trying to have one-line machine readable files. You can try to use https://www.textfixer.com/tools/remove-line-breaks.php to remove them, or else use the existing file.

**Comment by akhairna** [comment]
Hi David, 
   I used the link that you suggested to remove line breaks. Hopefully this fixes it.

Aniket Khairnar

**Comment by davidtrestini** [comment]
Sorry, I confused file names. "flux.txt" was the file I had uploaded, and did not have any line breaks. Can you please restore this file as it was (i.e. cancel you last commit)? What I meant what that "Raw data/arXiv/2410.16373v1/Equation (20).txt" has line breaks, and these should be removed.

**Comment by akhairna** [comment]
I am sorry, I wasn't attentive while changing the file. My text editor forcefully adds line breaks. That's why they were there. Anyway, it is fixed now. Let me know if there is still an issue.

**Review by davidtrestini — APPROVED** [review]
Although GitHub seems to indicate a change on "Core post-Newtonian quantities/Fluxes/Angular momentum flux/Circular orbits/Nonspinning/flux.txt", I have checked that there has been no change on this file.

**Comment by duetosymmetry** [comment]
@akhairna removed the line break that was at the end of the file.

I recommend that plain text files always end with a line break.

@akhairna can you rebase your commits and squash them all down into a single commit?

@davidtrestini I would recommend setting the repo to have a linear commit history, by only having PRs accepted as rebases — no merger commits

**Comment by davidtrestini** [comment]
@duetosymmetry are these now the settings you recommend?
Screenshot from 2024-12-12 00-07-10

**Comment by davidtrestini** [comment]
@duetosymmetry why do you recommend that text files end with a line break? Currently, I think all files do not end with a line break, but this can be (tediously) changed if useful.

**Comment by duetosymmetry** [comment]
@davidtrestini  PR settings: exactly

Re: line breaks: see https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

It's pretty straightforward to automate (I can do this and open a PR if you want)

**Comment by davidtrestini** [comment]
Would appreciate! Is it possible to automate so that all .txt files have newlines and double spaces removed, and have a linebreak at the end? Perhaps you can create an issue for this?

**Pull request merged**
